<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>CodersTea.DeeplyDep</RootNamespace>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackAsTool>true</PackAsTool>
        <ToolCommandName>deeplydep</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1"/>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="src\Core\" />
    </ItemGroup>
</Project>
